### ISSUE TITLE
Are updates required inside the docker?

### ISSUE THREAD

**Issue by 4fd81048-Brian** [VeeamHub/veeam-docker#3]
This might be a simple question, but are updates required inside a docker container? Is keeping the host patched sufficient? or should the container be destroyed and rebuilt on a regular basis?

I've used these commands to connect to the container and found there were updates
```
$sudo docker container ls -a -q --filter=name=vbrrepo
67ae5a808573
$sudo docker exec -u 0 -i 67ae5a808573 bash
#apt-get update
#apt-get upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  apt
The following packages will be upgraded:
  adduser base-files bash bsdutils ca-certificates dbus distro-info-data fdisk gir1.2-glib-2.0 libapparmor1 libblkid1 libc-bin libc6 libcryptsetup12 libdbus-1-3 libfdisk1
  libgirepository-1.0-1 libglib2.0-0 libglib2.0-data libgnutls30 libjson-c4 liblzma5 libmount1 libnss-systemd libpam-modules libpam-modules-bin libpam-runtime libpam-systemd libpam0g
  libpython3.8-minimal libpython3.8-stdlib libseccomp2 libsmartcols1 libsqlite3-0 libssl1.1 libsystemd0 libudev1 libuuid1 libx11-6 libx11-data login mount openssh-client openssh-server
  openssh-sftp-server openssl passwd python3-requests python3-urllib3 python3.8 python3.8-minimal systemd systemd-sysv systemd-timesyncd tzdata util-linux xz-utils
57 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

```

**Is your feature request related to a problem? Please describe.**
Just wanting to keep everything patched.

**Describe the solution you'd like**
Perhaps the unattended-upgrades package could be added to the container?  Documented in Ubuntu Server Guide:
https://ubuntu.com/server/docs/package-management
https://www.ubuntuupdates.org/package/core/focal/main/updates/unattended-upgrades
I don't know how to "reboot" a container after such updates though.

As for scheduling, I've realized there's no "good" time to apply updates or reboot a backup repository, so I just reboot when updates are available, installed and require it.

**Comment by tsightler** [comment]
The best way is to just rebuilt the image every so often, although I plan to update the Docker Hub image at least once a quarter as well.  While you theoretically can update the running docker (and it doesn't hurt anything) those updates are lost if the container is removed and re-run.  Although you could run docker commit after an update to commit the changes to a new image.

The docker image is a pretty low risk target, probably only at risk if there's a major vulnerability in, for example, the OpenSSH server, as it's truly the only port actually open and, even then, if you followed the firewalling advice, then the container SSH should only be accessible from the VBR server or a very limited subset of servers.

That being said, updating packages is never a bad idea.  I actually considered adding apt-get update as part of the entrypoint script, but it seemed a little like overkill.

What I'd suggest is, as it sounds like you already have an update process for the host, when you do that, add a script to rebuild the container and restart it, or at least pull the latest.  I admittedly need to rebuild the Docker Hub image right now as it's behind on updates and it the start of Q4.  I'll put that on my list.
