### ISSUE TITLE
Exposing too many ports starting from 2500

### ISSUE THREAD

**Issue by rafikc30** [VeeamHub/veeam-docker#5]
**Describe the bug**
I was trying to build a secure container using this repo and I could see we are recommended to open ports from 2500 to 3300 which is 800 ports. I want to understand the need for exposing this many ports. Where do we use this many ports? Do we need all the ports at starting itself? Or is it just a scalability measure that we may need the mentioned range of ports? If so, can we open the ports whenever we need?

**To Reproduce**
No steps to reproduce

**Comment by tsightler** [comment]
Hi @rafikc30.  This is the normal port range used by the data mover processes in VBR, as documented in the [user guide](https://helpcenter.veeam.com/docs/backup/vsphere/used_ports.html?ver=100).

In general these ports are assigned starting from the bottom of the range and working up so, in many environments, you can reduce the range.  However, simply failing to present ports that Veeam would expect to be open can lead to difficult to troubleshoot failure scenarios so the default behavior is to expose the entire standard port range that Veeam would expect for any standard repository.

Remember that there is nothing running in the container that is listening on these ports, unless Veeam has started a process on them, so there's not really much risk to them being exposed, however, you can use the host firewall to restrict access to this port range to only other systems running Veeam components (typically VBR server and proxies/mount servers, but there could be others based on how complex the environment is).

**Comment by rafikc30** [comment]
@tsightler Thanks for your reply. I have an additional question.
How do I know when will be the additional ports are used. As you said, the Veeam will start with the bottom, So If I give access to only 2500, it may work initially. But there will be a point where they might require additional ports. I'm looking for that scenario so that I can open additional ports whenever required and before they fail.

**Comment by tsightler** [comment]
As I said, it's really difficult to know.  In general each tasks needs ~2 ports (the exact number can very slightly based on the exact task), so more concurrent tasks = more required ports, but predicting the exact task count for any given environment can be difficult and, when the limit is hit, failures are difficult to predict.

I'd suggest testing with your desired maximum loads for a while and monitoring the highest used port, then giving yourself some headroom.

Note that the port range can also be modified in the Veeam settings when adding the system to **Managed Servers** the advanced button on the **SSH Connection** screen which allows you to define the port range that will be used for data transport, but defining a port range too small for the number of tasks you have will cause tasks to fail.

As I noted above, I don't believe there is any real risk in having ports open that don't have services listening on them so I don't really see how having 100 ports of nothing is better than 800 ports of nothing, but certainly you can test and define your settings as you see fit.

As this question is not really specific to this project, and is not really an outstanding issue, I'm going to close this issue for now, but if you have other questions feel free to ask here and I'll still attempt to respond.
