### ISSUE TITLE
High Availability of Secure Container

### ISSUE THREAD

**Issue by rafikc30** [VeeamHub/veeam-docker#6]
**Describe the bug**

I Have successfully created the docker using this repo. We use a clustered storage solution with three nodes. We want to make sure that the container is highly available even when one or two nodes are down from the storage cluster. To make it highly available, Can we simply create a CTDB cluster and run the container on all nodes with --restart unless-stopped. Then connecting the container using the virtual IP so that as long as the virtual IP is active we should be able to connect. Is there any problem with this approach, especially when a backup job is ongoing and Virtual IP transfer takes place at the same time? Since the containers are stateless, Do you see any problems with IP failover while an ongoing backup job is in progress?

Or Is there any recommended way of managing the container using any of the container orchestration tools? I'm raising this question since the repo or youtube video that posted on the topic doesn't cover the availability of the containers.

**Comment by tsightler** [comment]
I would need more details but at first glance I don't see any way this could possibly work as defined here.  The container is stateful, i.e. the repository filesystem is mounted to the container.  You can't just run the container on mulitple host and mount the same storage to each so what is your actual plan for failover of the storage to another node?  Also, during virtual IP failover connections to existing processes running in the prior container would fail, leading to sessions failures.

There is no recommended way to manage the container using container orchestration as that is beyond the scope of this project.  This project was designed to outline a method to take a single Linux host and enhance the security of the repository by leveraging standard, built-in Linux capabilities, Docker/containerization being one of those tools to isolate the Veeam access to the SSH connection and other processes.  Building a highly available, containerized repository, while a great goal, is well beyond the scope of this simple project.

**Comment by rafikc30** [comment]
@tsightler We are using software-defined NAS storage with a bind mount to the container. This means we can mount and make available the same storage on all of our three host machines.

So let's say first the veeam software connected to Host1 and were doing the backup. In the middle of a backup job, for some reason let's say that the host1 is down, the IP address will be moved to Host2, where there will be a container running with a similar configuration and the same storage system. For the veeam software, it is like an ssh reconnection while a backup job is in progress. In such cases, can Veeam software seamlessly continue the backup jobs?

**Comment by tsightler** [comment]
No, Veeam cannot seemlessly continue the backup jobs because, when Host1 fails, any Veeam processes running on that host will be lost.  Veeam will need to recognize these disconnect sessions, fail the sessions (and eventually the job) and everything might be OK on retry.  However, what you are attempting to setup is not supported by Veeam or this project.

**Comment by rafikc30** [comment]
@tsightler Thank you very much for your answer. I really appreciate it. I'm closing this issue since the solution is not officially supported.
