### ISSUE TITLE
Private Key not found...

### ISSUE THREAD

**Issue by WeaZzik** [VeeamHub/veeam-docker#7]
Hi everyone,
Today, i tried to use my proliant server as a repository with veeam, so i use "build-vbrrepo.sh" in vbrrepo to make it faster.
I have the "veeam-auth-key.pub" in /opt/veeam/keys but impossible to find the private key to connect to my docker...
So I decide to ask for help here.

( I'm on Ubuntu 20.04.1 LTS with an HP Proliant DL180 G6 if that can help )

**Comment by tsightler** [comment]
Which option are you choosing?  The script allows you to generate a new key, use an existing key file, or copy/paste an existing key in PEM format.  The latter two options both assume you have already generated your own public/private key pair so you would have to know where the private key is in this case (the script only needs the public key).  If you choose to generate a new key, the pub and private key are both created in the directory where you run the script.

**Comment by WeaZzik** [comment]
I used the first one where we generate new keys...
I FOUND it ! Thanks you, i didn't expect to found it in the Downloaded folder because the pub one was in /opt/veeam/keys...
Sorry for the waste of time...
